#!/usr/bin/env bun

import path from "path"
import { fileURLToPath } from "url"

const file = fileURLToPath(import.meta.url)
const dir = path.resolve(path.dirname(file), "../../..")
const src = path.join(dir, "docs/maas/modelcards.json")
const out = path.join(dir, "packages/opencode/src/provider/maas-generated.ts")

type Json = Record<string, unknown>

function arr(value: unknown) {
  return Array.isArray(value) ? value : []
}

function rec(value: unknown): Json {
  return typeof value === "object" && value !== null && !Array.isArray(value) ? (value as Json) : {}
}

function num(value: unknown) {
  if (typeof value === "number") return Number.isFinite(value) ? value : 0
  if (typeof value !== "string") return 0
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : 0
}

function text(value: unknown) {
  return typeof value === "string" ? value : ""
}

const data = rec(await Bun.file(src).json())
const models = arr(data.models)
const cards = models
  .map(rec)
  .filter((card) => card.model_type === "CHAT")
  .filter((card) => card.enabled === true && card.is_available === true && card.has_permission === true)
  .filter((card) => !text(card.model_name).includes("deep-research"))
  .filter((card) => text(card.model_name) !== "deepseek-v3.2")
  .map((card) => ({
    id: text(card.model_name),
    family: text(card.provider).toLowerCase(),
    context: num(card.context_length),
    output: num(card.output_limit || card.max_output_tokens || card.max_tokens),
    configs: arr(card.backend_model_list).flatMap((item) =>
      arr(rec(item).protocol_configs)
        .map(rec)
        .filter((cfg) => cfg.enabled !== false)
        .map((cfg) => ({
          api: text(cfg.api_type),
          ops: arr(cfg.supported_operations).map(text).filter(Boolean),
          caps: arr(cfg.capabilities).map(text).filter(Boolean),
          currency: text(cfg.currency) || "USD",
          prices: arr(rec(cfg.pricing).tiered_pricing)
            .map(rec)
            .map((price) => ({
              threshold: num(price.threshold),
              input: num(price.input_fee),
              output: num(price.output_fee),
              read: num(price.cached_input_fee),
              write:
                num(price.cache_creation_fee) ||
                num(price.explicit_cached_input_fee) ||
                num(rec(price.cache_creation_fees).ttl_5m),
            })),
        })),
    ),
  }))

const body = `// Auto-generated by script/generate-maas.ts - do not edit
export const cards = ${JSON.stringify(cards, null, 2)} as const
`

await Bun.write(out, body)
console.log(`Generated ${path.relative(dir, out)} with ${cards.length} models`)
