import { describe, expect, test } from "bun:test"
import path from "node:path"
import { BashTool } from "../../src/tool/bash"
import { Instance } from "../../src/project/instance"
import { Shell } from "../../src/shell/shell"
import { ShellOutput } from "../../src/shell/output"
import { MessageID, SessionID } from "../../src/session/schema"
import { tmpdir } from "../fixture/fixture"

const ctx = {
  sessionID: SessionID.make("ses_test"),
  messageID: MessageID.make(""),
  callID: "",
  agent: "build",
  abort: AbortSignal.any([]),
  messages: [],
  metadata: () => {},
  ask: async () => {},
}
const encoding = await ShellOutput.encoding()

describe("tool.bash output", () => {
  test("finishes when cancellation precedes process startup", async () => {
    await using tmp = await tmpdir()
    await Instance.provide({
      directory: tmp.path,
      fn: async () => {
        const tool = await BashTool.init()
        const result = await tool.execute(
          { command: "echo cancelled", description: "Handle prior cancellation" },
          { ...ctx, abort: AbortSignal.abort() },
        )
        expect(result.output).toContain("User aborted the command")
      },
    })
  })

  test("preserves split characters independently on stdout and stderr through EOF", async () => {
    await using tmp = await tmpdir()
    const file = path.join(tmp.path, "output.ts")
    await Bun.write(
      file,
      `const out = Buffer.from("中文🙂")
const err = Buffer.from("错误🚀")
process.stdout.write(out.subarray(0, 1))
await Bun.sleep(30)
process.stderr.write(err.subarray(0, 2))
await Bun.sleep(30)
process.stdout.write(out.subarray(1))
await Bun.sleep(30)
process.stderr.write(err.subarray(2))
`,
    )
    await Instance.provide({
      directory: tmp.path,
      fn: async () => {
        const tool = await BashTool.init()
        const prefix = /(?:powershell|pwsh)(?:\.exe)?$/i.test(Shell.acceptable()) ? "& " : ""
        const result = await tool.execute(
          {
            command: `${prefix}"${process.execPath.replaceAll("\\", "/")}" "${file.replaceAll("\\", "/")}"`,
            description: "Write split Unicode output",
          },
          ctx,
        )
        expect(result.metadata.exit).toBe(0)
        expect(result.output).toContain("中文🙂")
        expect(result.output).toContain("错误🚀")
        expect(result.output).not.toContain("�")
        expect(result.metadata.output).toBe(result.output)
      },
    })
  })

  test.skipIf(encoding !== "gbk")(
    "decodes mixed UTF-8 and CP936 PowerShell lines and an unterminated error",
    async () => {
      await using tmp = await tmpdir()
      const file = path.join(tmp.path, "native output.ps1")
      await Bun.write(
        file,
        `\uFEFF[Console]::OutputEncoding = [Text.Encoding]::GetEncoding(936)
[Console]::WriteLine('位置 行:1 字符: 124')
$bytes = [Text.Encoding]::UTF8.GetBytes("中文🙂 UTF-8\n")
[Console]::OpenStandardOutput().Write($bytes, 0, $bytes.Length)
[Console]::WriteLine('本地编码')
[Console]::Error.Write('不允许使用空管道元素。')
`,
      )
      await Instance.provide({
        directory: tmp.path,
        fn: async () => {
          const tool = await BashTool.init()
          const result = await tool.execute(
            {
              // Only this child process may execute the script generated by the test.
              command: `powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "${file.replaceAll("\\", "/")}"`,
              description: "Read native Chinese output",
            },
            ctx,
          )
          expect(result.metadata.exit).toBe(0)
          expect(result.output).toContain("位置 行:1 字符: 124")
          expect(result.output).toContain("中文🙂 UTF-8")
          expect(result.output).toContain("本地编码")
          expect(result.output).toContain("不允许使用空管道元素。")
          expect(result.output).not.toContain("�")
          expect(result.metadata.output).toBe(result.output)
        },
      })
    },
  )
})
