// Auto-generated by script/generate-maas.ts - do not edit
export const cards = [
  {
    "id": "qwen3.5-122b-a10b",
    "family": "alibaba",
    "context": 256000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES",
          "OPENAI_BATCH"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "RESPONSE",
          "FUNCTION_CALL",
          "ENABLE_BATCH"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 8e-7,
            "output": 0.0000064,
            "read": 8e-7,
            "write": 0.000001
          },
          {
            "threshold": 128000,
            "input": 0.000002,
            "output": 0.000016,
            "read": 0.000002,
            "write": 0.0000025
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 8e-7,
            "output": 0.0000064,
            "read": 8e-7,
            "write": 0.000001
          },
          {
            "threshold": 128000,
            "input": 0.000002,
            "output": 0.000016,
            "read": 0.000002,
            "write": 0.0000025
          }
        ]
      }
    ]
  },
  {
    "id": "qwen3.5-27b",
    "family": "alibaba",
    "context": 256000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES",
          "OPENAI_BATCH"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "RESPONSE",
          "FUNCTION_CALL",
          "ENABLE_BATCH"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 6e-7,
            "output": 0.0000048,
            "read": 6e-7,
            "write": 7.5e-7
          },
          {
            "threshold": 128000,
            "input": 0.0000018,
            "output": 0.0000144,
            "read": 0.0000018,
            "write": 0.00000225
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 6e-7,
            "output": 0.0000048,
            "read": 6e-7,
            "write": 6e-7
          },
          {
            "threshold": 128000,
            "input": 0.0000018,
            "output": 0.0000144,
            "read": 0.0000018,
            "write": 0.0000018
          }
        ]
      }
    ]
  },
  {
    "id": "qwen3.5-35b-a3b",
    "family": "alibaba",
    "context": 256000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "RESPONSE",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 4e-7,
            "output": 0.0000032,
            "read": 4e-7,
            "write": 5e-7
          },
          {
            "threshold": 128000,
            "input": 0.0000016,
            "output": 0.0000128,
            "read": 0.0000016,
            "write": 0.000002
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 4e-7,
            "output": 0.0000032,
            "read": 4e-7,
            "write": 4e-7
          },
          {
            "threshold": 128000,
            "input": 0.0000016,
            "output": 0.0000128,
            "read": 0.0000016,
            "write": 0.0000016
          }
        ]
      }
    ]
  },
  {
    "id": "qwen3.5-397b-a17b",
    "family": "alibaba",
    "context": 256000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES",
          "OPENAI_BATCH"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "RESPONSE",
          "FUNCTION_CALL",
          "ENABLE_BATCH"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000012,
            "output": 0.0000072,
            "read": 0.0000012,
            "write": 0.0000015
          },
          {
            "threshold": 128000,
            "input": 0.000003,
            "output": 0.000018,
            "read": 0.000003,
            "write": 0.00000375
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000012,
            "output": 0.0000072,
            "read": 0.0000012,
            "write": 0.0000012
          },
          {
            "threshold": 128000,
            "input": 0.000003,
            "output": 0.000018,
            "read": 0.000003,
            "write": 0.000003
          }
        ]
      }
    ]
  },
  {
    "id": "qwen3.5-flash",
    "family": "alibaba",
    "context": 1000000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES",
          "OPENAI_BATCH"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "RESPONSE",
          "FUNCTION_CALL",
          "ENABLE_BATCH"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 2e-7,
            "output": 0.000002,
            "read": 2e-7,
            "write": 2.5e-7
          },
          {
            "threshold": 128000,
            "input": 8e-7,
            "output": 0.000008,
            "read": 8e-7,
            "write": 0.000001
          },
          {
            "threshold": 256000,
            "input": 0.0000012,
            "output": 0.000012,
            "read": 0.0000012,
            "write": 0.0000015
          }
        ]
      }
    ]
  },
  {
    "id": "qwen3.6-plus",
    "family": "alibaba",
    "context": 1055000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES",
          "OPENAI_BATCH"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "RESPONSE",
          "FUNCTION_CALL",
          "ENABLE_BATCH"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000002,
            "output": 0.000012,
            "read": 0.000002,
            "write": 0.0000025
          },
          {
            "threshold": 256000,
            "input": 0.000008,
            "output": 0.000048,
            "read": 0.000008,
            "write": 0.00001
          }
        ]
      }
    ]
  },
  {
    "id": "claude-haiku-4-5",
    "family": "anthropic",
    "context": 200000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000001,
            "output": 0.000005,
            "read": 1e-7,
            "write": 0.00000125
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000001,
            "output": 0.000005,
            "read": 1e-7,
            "write": 0.00000125
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000001,
            "output": 0.000005,
            "read": 1e-7,
            "write": 0.00000125
          }
        ]
      }
    ]
  },
  {
    "id": "claude-opus-4-6",
    "family": "anthropic",
    "context": 1000000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          },
          {
            "threshold": 200000,
            "input": 0.00001,
            "output": 0.0000375,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          },
          {
            "threshold": 200000,
            "input": 0.00001,
            "output": 0.0000375,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          },
          {
            "threshold": 200000,
            "input": 0.00001,
            "output": 0.0000375,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          },
          {
            "threshold": 200000,
            "input": 0.00001,
            "output": 0.0000375,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      }
    ]
  },
  {
    "id": "claude-opus-4-7",
    "family": "anthropic",
    "context": 1000000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          },
          {
            "threshold": 200000,
            "input": 0.00001,
            "output": 0.0000375,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          },
          {
            "threshold": 200000,
            "input": 0.00001,
            "output": 0.0000375,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          },
          {
            "threshold": 200000,
            "input": 0.00001,
            "output": 0.0000375,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          },
          {
            "threshold": 200000,
            "input": 0.00001,
            "output": 0.0000375,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      }
    ]
  },
  {
    "id": "claude-sonnet-4-6",
    "family": "anthropic",
    "context": 1000000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000003,
            "output": 0.000015,
            "read": 3e-7,
            "write": 0.00000375
          },
          {
            "threshold": 200000,
            "input": 0.000006,
            "output": 0.0000225,
            "read": 3e-7,
            "write": 0.00000375
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000003,
            "output": 0.000015,
            "read": 3e-7,
            "write": 0.00000375
          },
          {
            "threshold": 200000,
            "input": 0.000006,
            "output": 0.0000225,
            "read": 3e-7,
            "write": 0.00000375
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000003,
            "output": 0.000015,
            "read": 3e-7,
            "write": 0.00000375
          },
          {
            "threshold": 200000,
            "input": 0.000006,
            "output": 0.0000225,
            "read": 3e-7,
            "write": 0.00000375
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000003,
            "output": 0.000015,
            "read": 3e-7,
            "write": 0.00000375
          },
          {
            "threshold": 200000,
            "input": 0.000006,
            "output": 0.0000225,
            "read": 3e-7,
            "write": 0.00000375
          }
        ]
      }
    ]
  },
  {
    "id": "deepseek-v4-pro",
    "family": "deepseek",
    "context": 1000000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000012,
            "output": 0.000024,
            "read": 0.0000024,
            "write": 0.000012
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000012,
            "output": 0.000024,
            "read": 0.0000024,
            "write": 0.000012
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000012,
            "output": 0.000024,
            "read": 0.000012,
            "write": 0.000012
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "WEB_SEARCH_BAIDU",
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000012,
            "output": 0.000024,
            "read": 0.000012,
            "write": 0.000012
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000012,
            "output": 0.000024,
            "read": 1e-7,
            "write": 0
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000012,
            "output": 0.000024,
            "read": 1e-7,
            "write": 0.000012
          }
        ]
      }
    ]
  },
  {
    "id": "gemini-3.1-flash-lite-preview",
    "family": "google",
    "context": 1048576,
    "output": 0,
    "configs": [
      {
        "api": "GEMINI",
        "ops": [
          "GEMINI_GENERATE_CONTENT",
          "GEMINI_STREAM_GENERATE_CONTENT"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "GENERATE_CONTENT"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 2.5e-7,
            "output": 0.0000015,
            "read": 2.5e-8,
            "write": 0
          }
        ]
      },
      {
        "api": "GEMINI",
        "ops": [
          "GEMINI_GENERATE_CONTENT",
          "GEMINI_STREAM_GENERATE_CONTENT"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "GENERATE_CONTENT"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 2.5e-7,
            "output": 0.0000015,
            "read": 2.5e-8,
            "write": 0
          }
        ]
      }
    ]
  },
  {
    "id": "gemini-3.1-pro-preview",
    "family": "google",
    "context": 1048576,
    "output": 0,
    "configs": [
      {
        "api": "GEMINI",
        "ops": [
          "GEMINI_GENERATE_CONTENT",
          "GEMINI_STREAM_GENERATE_CONTENT"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "GENERATE_CONTENT"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000002,
            "output": 0.000012,
            "read": 2e-7,
            "write": 0
          },
          {
            "threshold": 20000,
            "input": 0.000004,
            "output": 0.000018,
            "read": 4e-7,
            "write": 0
          }
        ]
      },
      {
        "api": "GEMINI",
        "ops": [
          "GEMINI_GENERATE_CONTENT",
          "GEMINI_STREAM_GENERATE_CONTENT"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "GENERATE_CONTENT"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000002,
            "output": 0.000012,
            "read": 2e-7,
            "write": 0
          },
          {
            "threshold": 20000,
            "input": 0.000004,
            "output": 0.000018,
            "read": 4e-7,
            "write": 0
          }
        ]
      }
    ]
  },
  {
    "id": "kimi-k2.5",
    "family": "kimi",
    "context": 224000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL",
          "IS_VISION"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000004,
            "output": 0.000021,
            "read": 8e-7,
            "write": 0.000005
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000004,
            "output": 0.000021,
            "read": 4e-7,
            "write": 0.000004
          }
        ]
      }
    ]
  },
  {
    "id": "kimi-k2.6",
    "family": "kimi",
    "context": 224000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000065,
            "output": 0.000027,
            "read": 6.5e-7,
            "write": 0.000008125
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL",
          "IS_VISION"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000065,
            "output": 0.000027,
            "read": 0.0000013,
            "write": 0.000008125
          }
        ]
      }
    ]
  },
  {
    "id": "minimax-m2.5",
    "family": "minimax",
    "context": 204800,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000021,
            "output": 0.0000084,
            "read": 4.2e-7,
            "write": 0.0000021
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000021,
            "output": 0.0000084,
            "read": 2.1e-7,
            "write": 0.0000021
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000021,
            "output": 0.0000084,
            "read": 4.2e-7,
            "write": 0.0000021
          }
        ]
      }
    ]
  },
  {
    "id": "minimax-m2.7",
    "family": "minimax",
    "context": 204800,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000021,
            "output": 0.0000084,
            "read": 4.2e-7,
            "write": 0.0000021
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000021,
            "output": 0.0000084,
            "read": 2.1e-7,
            "write": 0.0000021
          }
        ]
      }
    ]
  },
  {
    "id": "gpt-5.4-nano",
    "family": "openai",
    "context": 400000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 2e-7,
            "output": 0.00000125,
            "read": 2e-8,
            "write": 2e-7
          },
          {
            "threshold": 272000,
            "input": 4e-7,
            "output": 0.000001875,
            "read": 4e-8,
            "write": 4e-7
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 2e-7,
            "output": 0.00000125,
            "read": 2e-8,
            "write": 2e-7
          }
        ]
      }
    ]
  },
  {
    "id": "gpt-5.4-pro",
    "family": "openai",
    "context": 1050000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.00003,
            "output": 0.00018,
            "read": 0.000003,
            "write": 0.00003
          },
          {
            "threshold": 272000,
            "input": 0.00006,
            "output": 0.00027,
            "read": 0.000006,
            "write": 0.00006
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "RESPONSE",
          "COMPLETION"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.00003,
            "output": 0.00018,
            "read": 0.000003,
            "write": 0.00003
          },
          {
            "threshold": 272000,
            "input": 0.00006,
            "output": 0.00027,
            "read": 0.000006,
            "write": 0.00006
          }
        ]
      }
    ]
  },
  {
    "id": "gpt-5.4-mini",
    "family": "openai",
    "context": 400000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 7.5e-7,
            "output": 0.0000045,
            "read": 7.5e-8,
            "write": 7.5e-7
          },
          {
            "threshold": 272000,
            "input": 0.0000015,
            "output": 0.00000675,
            "read": 1.5e-7,
            "write": 0.0000015
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 7.5e-7,
            "output": 0.0000045,
            "read": 7.5e-8,
            "write": 7.5e-7
          },
          {
            "threshold": 272000,
            "input": 0.0000015,
            "output": 0.00000675,
            "read": 1.5e-7,
            "write": 0.0000015
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 7.5e-7,
            "output": 0.0000045,
            "read": 7.5e-8,
            "write": 7.5e-7
          },
          {
            "threshold": 272000,
            "input": 0.0000015,
            "output": 0.00000675,
            "read": 1.5e-7,
            "write": 0.0000015
          }
        ]
      }
    ]
  },
  {
    "id": "gpt-5.4",
    "family": "openai",
    "context": 1050000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000025,
            "output": 0.000015,
            "read": 2.5e-7,
            "write": 0.0000025
          },
          {
            "threshold": 272000,
            "input": 0.000005,
            "output": 0.0000225,
            "read": 5e-7,
            "write": 0.000005
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000025,
            "output": 0.000015,
            "read": 2.5e-7,
            "write": 0.0000025
          },
          {
            "threshold": 272000,
            "input": 0.000005,
            "output": 0.0000225,
            "read": 5e-7,
            "write": 0.000005
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000025,
            "output": 0.000015,
            "read": 2.5e-7,
            "write": 0.0000025
          },
          {
            "threshold": 272000,
            "input": 0.000005,
            "output": 0.0000225,
            "read": 5e-7,
            "write": 0.000005
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000025,
            "output": 0.000015,
            "read": 2.5e-7,
            "write": 0.0000025
          },
          {
            "threshold": 272000,
            "input": 0.000005,
            "output": 0.0000225,
            "read": 5e-7,
            "write": 0.000005
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000025,
            "output": 0.000015,
            "read": 2.5e-7,
            "write": 0.0000025
          },
          {
            "threshold": 272000,
            "input": 0.000005,
            "output": 0.0000225,
            "read": 5e-7,
            "write": 0.000005
          }
        ]
      }
    ]
  },
  {
    "id": "mimo-v2.5-pro",
    "family": "xiaomi",
    "context": 1000000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000007,
            "output": 0.000021,
            "read": 0.0000014,
            "write": 0.000007
          },
          {
            "threshold": 256000,
            "input": 0.000014,
            "output": 0.000042,
            "read": 0.0000028,
            "write": 0.000014
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000007,
            "output": 0.000021,
            "read": 0.0000014,
            "write": 0
          },
          {
            "threshold": 256000,
            "input": 0.000014,
            "output": 0.000042,
            "read": 0.0000028,
            "write": 0
          }
        ]
      }
    ]
  },
  {
    "id": "glm-5",
    "family": "zai",
    "context": 200000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000004,
            "output": 0.000018,
            "read": 0.000004,
            "write": 0.000004
          },
          {
            "threshold": 32000,
            "input": 0.000006,
            "output": 0.0000225,
            "read": 0.000006,
            "write": 0.000006
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000004,
            "output": 0.000018,
            "read": 0.000004,
            "write": 0.000004
          }
        ]
      }
    ]
  },
  {
    "id": "mimo-v2.5",
    "family": "xiaomi",
    "context": 1000000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL",
          "IS_VISION"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000028,
            "output": 0.000014,
            "read": 5.6e-7,
            "write": 0.0000028
          },
          {
            "threshold": 256000,
            "input": 0.0000056,
            "output": 0.000028,
            "read": 0.00000112,
            "write": 0.0000056
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.0000028,
            "output": 0.000014,
            "read": 5.6e-7,
            "write": 0
          },
          {
            "threshold": 256000,
            "input": 0.0000056,
            "output": 0.000028,
            "read": 0.00000112,
            "write": 0
          }
        ]
      }
    ]
  },
  {
    "id": "glm-5.1",
    "family": "zai",
    "context": 202000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000006,
            "output": 0.000024,
            "read": 0.0000012,
            "write": 0.0000075
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000006,
            "output": 0.000024,
            "read": 0.0000012,
            "write": 0.0000075
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000006,
            "output": 0.000024,
            "read": 0.000006,
            "write": 0.000006
          }
        ]
      }
    ]
  },
  {
    "id": "mimo-v2-flash",
    "family": "xiaomi",
    "context": 256000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 7e-7,
            "output": 0.0000021,
            "read": 7e-8,
            "write": 0
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 7e-7,
            "output": 0.0000021,
            "read": 7e-8,
            "write": 7e-7
          }
        ]
      }
    ]
  },
  {
    "id": "deepseek-v4-flash",
    "family": "deepseek",
    "context": 1000000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000001,
            "output": 0.000002,
            "read": 2e-7,
            "write": 0
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000001,
            "output": 0.000002,
            "read": 2e-7,
            "write": 0.000001
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000001,
            "output": 0.000002,
            "read": 0.000001,
            "write": 0
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000001,
            "output": 0.000002,
            "read": 0.000001,
            "write": 0.000001
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS"
        ],
        "caps": [
          "COMPLETION",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000001,
            "output": 0.000002,
            "read": 2e-8,
            "write": 0
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "MESSAGES_API",
          "FUNCTION_CALL"
        ],
        "currency": "CNY",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000001,
            "output": 0.000002,
            "read": 2e-8,
            "write": 0.000001
          }
        ]
      }
    ]
  },
  {
    "id": "gpt-5.5",
    "family": "openai",
    "context": 1050000,
    "output": 0,
    "configs": [
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.00003,
            "read": 5e-7,
            "write": 0.000005
          },
          {
            "threshold": 272000,
            "input": 0.00001,
            "output": 0.000045,
            "read": 0.000001,
            "write": 0.00001
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.00003,
            "read": 5e-7,
            "write": 0.000005
          },
          {
            "threshold": 272000,
            "input": 0.00001,
            "output": 0.000045,
            "read": 0.000001,
            "write": 0.00001
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.00003,
            "read": 5e-7,
            "write": 0.000005
          },
          {
            "threshold": 272000,
            "input": 0.00001,
            "output": 0.000045,
            "read": 0.000001,
            "write": 0.00001
          }
        ]
      },
      {
        "api": "OPENAI",
        "ops": [
          "OPENAI_CHAT_COMPLETIONS",
          "OPENAI_COMPLETIONS",
          "OPENAI_RESPONSES"
        ],
        "caps": [
          "IS_VISION",
          "COMPLETION",
          "FUNCTION_CALL",
          "RESPONSE"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.00003,
            "read": 5e-7,
            "write": 0.000005
          },
          {
            "threshold": 272000,
            "input": 0.00001,
            "output": 0.000045,
            "read": 0.000001,
            "write": 0.00001
          }
        ]
      }
    ]
  },
  {
    "id": "claude-opus-4-8",
    "family": "anthropic",
    "context": 1000000,
    "output": 0,
    "configs": [
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      },
      {
        "api": "ANTHROPIC",
        "ops": [
          "ANTHROPIC_MESSAGES"
        ],
        "caps": [
          "IS_VISION",
          "FUNCTION_CALL",
          "MESSAGES_API"
        ],
        "currency": "USD",
        "prices": [
          {
            "threshold": 0,
            "input": 0.000005,
            "output": 0.000025,
            "read": 5e-7,
            "write": 0.00000625
          }
        ]
      }
    ]
  }
] as const
